
// This file has been generated by the GUI designer. Do not modify.
namespace WinuxDB
{
	public partial class wCreateTable
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action applyAction;

		private global::Gtk.Action actAddColumn;

		private global::Gtk.Action actDelete;

		private global::Gtk.VBox vboxMain;

		private global::Gtk.Toolbar toolbar1;

		private global::Gtk.Table table1;

		private global::Gtk.Button btnRefreshTables;

		private global::Gtk.ComboBox cmbTableList;

		private global::Gtk.Label lblSelectedTable;

		private global::Gtk.Label lblTableName;

		private global::Gtk.Label lblTableTitle;

		private global::Gtk.Entry txtTableName;

		private global::Gtk.Entry txtTableTitle;

		private global::Gtk.Table table2;

		private global::Gtk.CheckButton chbMainTable;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.Toolbar toolbar2;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TreeView tblColumns;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget WinuxDB.wCreateTable
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.applyAction = new global::Gtk.Action("applyAction", null, global::Mono.Unix.Catalog.GetString("Create table"), "gtk-apply");
			w1.Add(this.applyAction, null);
			this.actAddColumn = new global::Gtk.Action("actAddColumn", null, global::Mono.Unix.Catalog.GetString("Add"), "gtk-add");
			w1.Add(this.actAddColumn, null);
			this.actDelete = new global::Gtk.Action("actDelete", null, global::Mono.Unix.Catalog.GetString("Delete"), "gtk-delete");
			w1.Add(this.actDelete, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "WinuxDB.wCreateTable";
			this.Title = global::Mono.Unix.Catalog.GetString("Create Table");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Modal = true;
			// Container child WinuxDB.wCreateTable.Gtk.Container+ContainerChild
			this.vboxMain = new global::Gtk.VBox();
			this.vboxMain.Name = "vboxMain";
			// Container child vboxMain.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar1\'><toolitem name=\'applyAction\' action=\'applyAction\'/><" +
					"/toolbar></ui>");
			this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar1")));
			this.toolbar1.Name = "toolbar1";
			this.toolbar1.ShowArrow = false;
			this.toolbar1.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
			this.toolbar1.IconSize = ((global::Gtk.IconSize)(3));
			this.vboxMain.Add(this.toolbar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.toolbar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table(((uint)(5)), ((uint)(3)), false);
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			this.table1.BorderWidth = ((uint)(10));
			// Container child table1.Gtk.Table+TableChild
			this.btnRefreshTables = new global::Gtk.Button();
			this.btnRefreshTables.CanFocus = true;
			this.btnRefreshTables.Name = "btnRefreshTables";
			this.btnRefreshTables.UseUnderline = true;
			global::Gtk.Image w3 = new global::Gtk.Image();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-refresh", global::Gtk.IconSize.Menu);
			this.btnRefreshTables.Image = w3;
			this.table1.Add(this.btnRefreshTables);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.btnRefreshTables]));
			w4.LeftAttach = ((uint)(2));
			w4.RightAttach = ((uint)(3));
			w4.YPadding = ((uint)(4));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.cmbTableList = global::Gtk.ComboBox.NewText();
			this.cmbTableList.Name = "cmbTableList";
			this.table1.Add(this.cmbTableList);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.cmbTableList]));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.YPadding = ((uint)(5));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblSelectedTable = new global::Gtk.Label();
			this.lblSelectedTable.Name = "lblSelectedTable";
			this.lblSelectedTable.LabelProp = global::Mono.Unix.Catalog.GetString("Selected Table");
			this.table1.Add(this.lblSelectedTable);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.lblSelectedTable]));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblTableName = new global::Gtk.Label();
			this.lblTableName.Name = "lblTableName";
			this.lblTableName.LabelProp = global::Mono.Unix.Catalog.GetString("Table Name");
			this.table1.Add(this.lblTableName);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.lblTableName]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblTableTitle = new global::Gtk.Label();
			this.lblTableTitle.Name = "lblTableTitle";
			this.lblTableTitle.LabelProp = global::Mono.Unix.Catalog.GetString("Table Title");
			this.table1.Add(this.lblTableTitle);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.lblTableTitle]));
			w8.TopAttach = ((uint)(2));
			w8.BottomAttach = ((uint)(3));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtTableName = new global::Gtk.Entry();
			this.txtTableName.CanFocus = true;
			this.txtTableName.Name = "txtTableName";
			this.txtTableName.IsEditable = true;
			this.txtTableName.InvisibleChar = '●';
			this.table1.Add(this.txtTableName);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.txtTableName]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtTableTitle = new global::Gtk.Entry();
			this.txtTableTitle.CanFocus = true;
			this.txtTableTitle.Name = "txtTableTitle";
			this.txtTableTitle.IsEditable = true;
			this.txtTableTitle.InvisibleChar = '●';
			this.table1.Add(this.txtTableTitle);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.txtTableTitle]));
			w10.TopAttach = ((uint)(2));
			w10.BottomAttach = ((uint)(3));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vboxMain.Add(this.table1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.table1]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.table2 = new global::Gtk.Table(((uint)(2)), ((uint)(2)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.chbMainTable = new global::Gtk.CheckButton();
			this.chbMainTable.CanFocus = true;
			this.chbMainTable.Name = "chbMainTable";
			this.chbMainTable.Label = global::Mono.Unix.Catalog.GetString("This is main table");
			this.chbMainTable.DrawIndicator = true;
			this.chbMainTable.UseUnderline = true;
			this.table2.Add(this.chbMainTable);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table2[this.chbMainTable]));
			w12.XPadding = ((uint)(5));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vboxMain.Add(this.table2);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.table2]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator();
			this.hseparator1.Name = "hseparator1";
			this.vboxMain.Add(this.hseparator1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.hseparator1]));
			w14.Position = 3;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar2\'><toolitem name=\'actAddColumn\' action=\'actAddColumn\'/" +
					"><toolitem name=\'actDelete\' action=\'actDelete\'/></toolbar></ui>");
			this.toolbar2 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar2")));
			this.toolbar2.Name = "toolbar2";
			this.toolbar2.ShowArrow = false;
			this.toolbar2.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
			this.toolbar2.IconSize = ((global::Gtk.IconSize)(3));
			this.vboxMain.Add(this.toolbar2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.toolbar2]));
			w15.Position = 4;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.tblColumns = new global::Gtk.TreeView();
			this.tblColumns.CanFocus = true;
			this.tblColumns.Name = "tblColumns";
			this.tblColumns.EnableSearch = false;
			this.GtkScrolledWindow1.Add(this.tblColumns);
			this.vboxMain.Add(this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.GtkScrolledWindow1]));
			w17.Position = 5;
			this.Add(this.vboxMain);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 571;
			this.DefaultHeight = 543;
			this.Show();
			this.applyAction.Activated += new global::System.EventHandler(this.OnActCreateActivated);
			this.actAddColumn.Activated += new global::System.EventHandler(this.OnActAddColumnActivated);
			this.actDelete.Activated += new global::System.EventHandler(this.OnActDeleteActivated);
			this.cmbTableList.Changed += new global::System.EventHandler(this.OnCmbTableListChanged);
			this.btnRefreshTables.Clicked += new global::System.EventHandler(this.OnBtnRefreshTablesClicked);
			this.tblColumns.KeyPressEvent += new global::Gtk.KeyPressEventHandler(this.OnTblColumnsKeyPressEvent);
		}
	}
}
