
// This file has been generated by the GUI designer. Do not modify.
namespace WinuxDB
{
	public partial class wLogin
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget WinuxDB.wLogin
			this.Name = "WinuxDB.wLogin";
			this.Title = global::Mono.Unix.Catalog.GetString("Authorization");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Modal = true;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 217;
			this.Show();
		}
	}
}
